export default function saveUser(user) {
    localStorage.setItem("me.enter_year", user.EnterYear)
    localStorage.setItem("me.name", user.Name)
    localStorage.setItem("me.id", user.ID)
    localStorage.setItem("me.barcode", user.Barcode)
    localStorage.setItem("me.grade", user.Grade)
    localStorage.setItem("me.class", user.Class)
    localStorage.setItem("me.number", user.Number)
    localStorage.setItem("me.year", user.BirthYear)
    localStorage.setItem("me.month", user.BirthMonth)
    localStorage.setItem("me.day", user.BirthDay)
    localStorage.setItem("me.sex", user.Sex)
    localStorage.setItem("me.roles", user.Roles)
    localStorage.setItem("me.residence", user.Residence)
}